### ISSUE TITLE
It has trouble when i compile in ubuntu 16.04

### ISSUE THREAD

**Issue by RogerZheng** [Kitt-AI/snowboy#218]
It has trouble when i compile in ubuntu 16.04.
I has tried to add macro _GLIBCXX_USE_CXX11_ABI,but it is useless.
+#undef _GLIBCXX_USE_CXX11_ABI
+#define _GLIBCXX_USE_CXX11_ABI 0
And I try to add 'add_definitions(-std=c++11)' to cmake,but it is useless too.
The log is like this:
../../KWD/KittAi/src/libKITTAI.so: undefined reference to add`snowboy::SnowboyDetect::SetSensitivity(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../../KWD/KittAi/src/libKITTAI.so: undefined reference to `snowboy::SnowboyDetect::SnowboyDetect(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'

**Comment by chenguoguo** [comment]
Have you tried wrappers like this?

https://github.com/Kitt-AI/snowboy/issues/99

**Comment by charleschen84** [comment]
Could you give me a libsnow-detector.a to fix it？like aarch64-ubuntu1604？When I compile alexa-client-sdk from amzon，it can't be compiled because of it.

**Comment by RogerZheng** [comment]
Could you give me a libsnow-detector.a to fix it？like aarch64-ubuntu1604？When I compile alexa-client-sdk from amazon，it can't be compiled because of it.

**Comment by xuchen** [comment]
send an email to snowboy@kitt.ai, I'll give you a version I just compiled today

**Comment by chenguoguo** [comment]
You can also use a wrapper https://github.com/Kitt-AI/snowboy/issues/99

**Comment by chenguoguo** [comment]
Nvm, it's the same thread... Replied from email and didn't see the history...
