### PR TITLE
Add support for Node > 8

### LINKED ISSUE #536: Update node-pre-gyp dependency
I was testing out Snowboy for Node in one of my project and I found it really awesome, but after pushing the code on GitHub I was presented with this

image

image

An `npm ls` of those two vulnerable deps brought me to this

image

I haven't checked out what type of vulnerabilities do that deps expose, but the `node-pre-gyp` version you are using is quite outdated, so it would be great if you could update it.

### PR DESCRIPTION
**Pull request by Dabolus**
This PR adds support for Node > 8 by updating the `node-pre-gyp` dependency of the Node binding for Snowboy. I tested it locally using Node 10.15.0 and it builds without any issues. Updating this dependency will also fix some severe vulnerabilities caused by the outdated dependency. The only small downside is that `node-pre-gyp` dropped the support for Node 0.10.x (which was released more than 5 years ago and reached its end of life 2 years ago, so it shouldn't be a big problem). Node 10 and 11 have also been added to Travis matrix.

Fixes #536

### CODE REVIEW

**Comment by evancohen** [comment]
Happy New Year! I think this is a worth while change.  
It's 2019, the node bindings should support  Node > 8 :rofl:. Happy to test this out and confirm it works if that will get it merged.

**Comment by evancohen** [comment]
I made this change on my own local branch https://github.com/evancohen/snowboy/commit/a6e3c830b525f8857924b0aa5690e7f19597a815, and it looks like the build for Node 8.0.0 failed: https://travis-ci.org/evancohen/snowboy/builds/477664987  

@Dabolus do you know why that might be? It looks like node-pre-gyp isn't found, *just* for that version, on both OSX and Linux. For some odd reason the work-around that I had in [`.travis.yml#L52`](https://github.com/evancohen/snowboy/blob/master/.travis.yml#L52) doesn't work in this case.

**Comment by Dabolus** [comment]
@evancohen that's really strange. I tried to build on Travis too with my repo and I had the exact same issue. However, if I follow the same steps with Node 8.0.0 installed with nvm on my local machine, everything works like a charm. Still investigating.

**Comment by evancohen** [comment]
This is likely to do with some funky change that was made in the way that the 8.x version of Node/npm reads or sets environmental variables.  

Speaking of major releases always having some bugs, maybe using the latest version of 8.x will solve the issue! I kicked off a build with that (https://github.com/evancohen/snowboy/commit/2d51ae0ab2afb3205e5105555546c28a89f805fb) here:
https://travis-ci.org/evancohen/snowboy/builds/478843913

**Comment by Dabolus** [comment]
Glad to know that worked! Updating my branch too right now. It would be great to have some feedback from Snowboy maintainers, though.

**Comment by WoodySlum** [comment]
Hi, thanks for fixing. Would it be possible to merge ? I had to disable snowboy in my app due to unsupport of node 10 on rpi.

**Review by imrrahul — APPROVED** [review]
LGTM ! It will be very useful if added in documentation

**Comment by mreinstein** [comment]
can we please get this merged? Node 6 is on the verge of being deprecated https://nodejs.org/en/about/releases/

**Comment by evancohen** [comment]
I did some investigating and I put together an easy way to install snowboy (v1.3.1) that is compatible with Node 6-12 and has precompiled binaries for darwin (OSX), x64 (most Linux), and ARM (Pi). All you've got to do is run:
```
npm install snoyboy@sonus
```

**Comment by louistiti** [comment]
Thanks @evancohen!

It works like a charm.

**Comment by sdetweil** [comment]
@evancohen Evan, the npm install snoyboy@sonus, did not work on node 10.17(today), ubuntu on armv71. same compile failure as before

**Comment by evancohen** [comment]
Not sure why this stopped working all of a sudden, I'll take a look when I get the chance.  
Happy thanksgiving 🦃

**Comment by MrWook** [comment]
Any updates for this? 
Would love to use snowboy

**Comment by xXKeyleXx** [comment]
For those who get the nan error and use Yarn you can do add the following to your package.json:
```
  "resolutions": {
    "snowboy/node-pre-gyp": "^0.14.0"
  }
```

**Comment by louistiti** [comment]
Hello everyone :wave:,

Since a while, with the `npm install snoyboy@sonus` fix I was getting the following error after the install:

```
Error: Cannot find module 'nan'
```

I forked it and moved the `nan` module from the devDependencies to dependencies in the `package.json` file.
Also, I updated `node-pre-gyp` to `@mapbox/node-pre-gyp` as the original one seems deprecated.

[My fork](https://github.com/leon-ai/snowboy) is currently working with Node.js 14.16.0.

Hope that helps.

**Comment by Dabolus** [comment]
Well, my PR is quite outdated and this repo has been abandoned since a long time, so I will close it to tidy things up. Check one of the many forks if you need to use snowboy in applications using an up-to-date Node.js version.
