### ISSUE TITLE
pthread_join issue

### ISSUE THREAD

**Issue by aazimh** [Kitt-AI/snowboy#24]
Hi guys,

I had the snowboy demo working just fine for me but after tinkering around with things I've managed to break it somehow and can't figure out why. This is what I get when I run the demo script with a personal model:

`Expression 'paTimedOut' failed in 'src/os/unix/pa_unix_util.c', line: 387
Expression 'PaUnixThread_New( &stream->thread, &CallbackThreadFunc, stream, 1., stream->rtSched )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2998
Expression 'pthread_join( self->thread, &pret )' failed in 'src/os/unix/pa_unix_util.c', line: 441`

There's also the usual ALSA and jack server could not be started errors but these were there before too and didn't cause any issues. The quoted error is the new one.

Any help would be appreciated - thanks.

**Comment by chenguoguo** [comment]
This looks like a PortAudio/ALSA issue. I haven't seen this particular. What have you done? Will it help if you reinstall PortAudio and re-configure ALSA?

**Comment by aazimh** [comment]
Okay, so I tried uninstalling PortAudio by running 'pip uninstall pyaudio' first and then 'apt-get purge python-pyaudio python3-pyaudio'. I then reinstalled in the opposite order but the 'pip install pyaudio' is throwing up another weird error:

`Installing collected packages: pyaudio
  Found existing installation: PyAudio 0.2.8
    DEPRECATION: Uninstalling a distutils installed project (pyaudio) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling PyAudio-0.2.8:
      Successfully uninstalled PyAudio-0.2.8
  Running setup.py install for pyaudio ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-yI1SXc/pyaudio/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Emn4Mi-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-armv7l-2.7
    copying src/pyaudio.py -> build/lib.linux-armv7l-2.7
    running build_ext
    building '_portaudio' extension
    creating build/temp.linux-armv7l-2.7
    creating build/temp.linux-armv7l-2.7/src
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c src/_portaudiomodule.c -o build/temp.linux-armv7l-2.7/src/_portaudiomodule.o
    src/_portaudiomodule.c:28:20: fatal error: Python.h: No such file or directory
     #include "Python.h"
                        ^
    compilation terminated.
    error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
    
    ----------------------------------------
  Rolling back uninstall of PyAudio
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-yI1SXc/pyaudio/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Emn4Mi-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-yI1SXc/pyaudio/`

Sorry for the super long paste, there was more but this is the last bit of it and seems most relevant. As for what I could have done to make this happen, the only thing I can think of is removing PulseAudio which I had installed last week or so. Also, my 'rec' and 'play' commands work fine on their own if that helps.

**Comment by aazimh** [comment]
More updates! After a reboot, the demo now works with the universal model but using a personal model gives me the same error in the OP. Going to try training another model and use that now.

**Comment by chenguoguo** [comment]
It's great that rebooting solves the issue. It's wired that it works for the universal model, but not the personal model. By "error in the OP" you mean the paTimeOut problem? This shouldn't really happen, because changing the models only affects the Snowboy internal code, not portaudio.

**Comment by aazimh** [comment]
Yes, that error. It's hit and miss now, works with the universal model sometimes and not the personal one, and other times vice versa. Makes no sense to me either as to why it happens. When it does work though, I can see console output detecting my keyword, but I don't hear the 'ding' sound I'm supposed to - suggests that it is a portaudio configuration issue.

Do you know if there's a proper way to reinstall portaudio then? Might give that a shot. 

For context, I want to record from a USB webcam but play back through my HDMI monitor. Even though 'rec' and 'play' work fine, maybe the Snowboy code is being thrown off by my setup?

**Comment by chenguoguo** [comment]
Hmm, this is quite confusing... I haven't seen this issue before.

I've used a USB webcam to capture the audio, and played back the "ding" sound through HDMI monitor. It worked for me, so I think the setup should be fine. I suspect it's some other configuration problems, maybe caused by uninstall pulseaudio? Sometimes when you do uninstall the OS uninstalls dependencies that it "thinks" is not necessary. If you don't have a lot of stuff installed on your Pi (you are using Pi right?), it might be easier to give it a fresh installation?

**Comment by aazimh** [comment]
Yes, using a Pi. Unfortunately there is a lot of other stuff I've got on it so I'm trying to avoid a fresh install if possible because I don't want to setup all the other stuff again :) 

You're right though, when I installed it the first time it worked fine recording through the webcam and playing the ding through HDMI. It must be the pulseaudio stuff that's gone wrong. Anyway, I'll keep Googling :) thanks for your help! Let me know if you have a revelation about what it could be :p

**Comment by aazimh** [comment]
Just an update, I ended up re-installing Raspbian and it works fine now :) thanks for the suggestion!

**Comment by chenguoguo** [comment]
That seems to be the ultimate solution :-)

**Comment by YuechuanLi** [comment]
ERROR:ws_tts:Error: __aenter__
ERROR:ws_tts:Error: __aenter__
