### ISSUE TITLE
Python raspbian

### ISSUE THREAD

**Issue by yodakohl** [Kitt-AI/snowboy#191]
When using python or python3 on the current raspian version i'm getting following error:
```
Traceback (most recent call last):
  File "demo.py", line 27, in <module>
    detector = snowboydecoder.HotwordDetector(model, sensitivity=0.5)
  File "/home/pi/snowboy/examples/Python3/snowboydecoder.py", line 91, in __init__
    resource_filename=resource.encode(), model_str=model_str.encode())
TypeError: __init__() got an unexpected keyword argument 'resource_filename'
```

The swig version used is Version 2.0.12

This works fine on my desktop using swig Version 3.0.10

For python 2 this can be resolved using this patch
```
diff --git a/examples/Python/snowboydecoder.py b/examples/Python/snowboydecoder.py
index e13781d..bee74a8 100644
--- a/examples/Python/snowboydecoder.py
+++ b/examples/Python/snowboydecoder.py
@@ -88,7 +88,7 @@ class HotwordDetector(object):
         model_str = ",".join(decoder_model)
 
         self.detector = snowboydetect.SnowboyDetect(
-            resource_filename=resource.encode(), model_str=model_str.encode())
+           resource.encode(), model_str.encode())
         self.detector.SetAudioGain(audio_gain)
         self.num_hotwords = self.detector.NumHotwords()
```
 or by using the snowboydecoder.py generated by the newer swig version. However for 
python3 this leads to another error message

```
Traceback (most recent call last):
  File "demo.py", line 27, in <module>
    detector = snowboydecoder.HotwordDetector(model, sensitivity=0.5)
  File "/home/pi/snowboy/examples/Python3/snowboydecoder.py", line 91, in __init__
    resource.encode(), model_str.encode())
  File "/home/pi/snowboy/examples/Python3/snowboydetect.py", line 79, in __init__
    this = _snowboydetect.new_SnowboyDetect(*args)
TypeError: in method 'new_SnowboyDetect', argument 1 of type 'std::string const &'
```
On my desktop pc everything is working fine

**Comment by yodakohl** [comment]
After updating to swig Version 3.0.12 the issue is gone
